# Site settings
baseurl = "http://otselo.eu/"
defaultContentLanguage = "bg"
theme = "hugo_theme_robust"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"
disqusShortname = "XYW"

[params]
    
[Languages]
[Languages.bg]
    title = "От село"
[Languages.en]
    title = "From the village"
[taxonomies]
    tags = "tags"
    categories = "categories"
    

   
